// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lkclreldnbejfubzhube.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxrY2xyZWxkbmJlamZ1YnpodWJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzODg2MjcsImV4cCI6MjA1Nzk2NDYyN30.1Jz-zMLWVTRePFx947cGCVAYNKFswD25FNMTPGyciRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);